import { type Metadata } from 'next'
import './globals.css'
import Header from '@/components/Header'
import { ClerkProvider } from '@clerk/nextjs'
import Sidebar from '@/components/Sidebar'

export const metadata: Metadata = {
  title: 'Clerk Next.js Quickstart',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className="bg-gray-50 text-gray-800 min-h-screen">
        <ClerkProvider>
          <Header />
          
          {/* Main container with sidebar layout */}
          <div className="flex h-[calc(100vh-4rem)]"> {/* Adjust height to account for header */}
            {/* Sidebar - Fixed 20% width */}
            <Sidebar />
            
            {/* Main content area - 80% width */}
            <main className="flex-1 bg-white shadow-lg rounded-xl p-6 m-4 ml-0 overflow-y-auto scrollbar-hide">
              {children}
            </main>
          </div>
        </ClerkProvider>
      </body>
    </html>
  )
}