// app/layout.tsx
import { type Metadata } from 'next'
import './globals.css'
import Header from '@/components/Header'
import { ClerkProvider } from '@clerk/nextjs'
import Sidebar from '@/components/Sidebar'

export const metadata: Metadata = {
  title: 'Clerk Next.js Quickstart',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className="bg-gray-50 text-gray-800 min-h-screen">
        <ClerkProvider>
          <Header />
          
           <div className='flex min-h-screen'>
             <Sidebar  />

            <div className='flex-1 p-4 overflow-y-auto scrollbar-hide'>
              {children}
            </div>
           </div>
          
                    
        </ClerkProvider>
      </body>
    </html>
  )
}
